name: CD-CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.pusher.email != 'version-bump@flossware.org'
    runs-on: ubuntu-latest

    steps:
      - name: Updating runner
        run: sudo apt-get update

      - name: Install ncurses development libraries
        run: sudo apt-get install -y libncurses-dev

      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Preparing settings.xml
        uses: s4u/maven-settings-action@v4.0.0
        with:
          githubServer: false
          servers: |
            [
              {
                "id": "packagecloud-flossware",
                "configuration": {
                  "httpHeaders": {
                    "property": {
                      "name": "Authorization",
                      "value": "Bearer ${{ secrets.PACKAGECLOUD_TOKEN }}"
                    }
                  }
                }
              }
            ]

      - name: Setup git credentials for version bumps
        run: |
          git config --global user.name 'Version Bump'
          git config --global user.email 'version-bump@flossware.org'

      - name: Incrementing pom.xml version
        run: "mvn -U build-helper:parse-version versions:set -DnewVersion=\\${parsedVersion.majorVersion}.\\${parsedVersion.nextMinorVersion} versions:commit"

      - name: Ensure latest dependencies in pom.xml
        run: "mvn -Dincludes='org.junit.jupiter:*,org.mockito:*,org.assertj:*' -DgenerateBackupPoms=false versions:update-properties"

      - name: Building
        run: "mvn -U clean install"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'target/surefire-reports/*.xml'
          check_name: 'Unit Test Results'

      - name: Deploy to packagecloud.io
        run: "mvn -DskipTests deploy"

      - name: Checkin and tag to github
        run: "mvn scm:checkin scm:tag"
